"""P7.3d T-regress (b): hangzhou's committed artifacts regenerate BYTE-IDENTICALLY through the
scenario-parameterised code (``BRIEF_39`` §4, Amendment A3).

*"No change to hz1x1 behaviour: every hz1x1 artifact must regenerate byte-identically through the
parameterised code"* is the load-bearing promise of P7.3d, and this file is where it is checked
against the REAL work directories, by the REAL ``report`` functions, into ``tmp_path``.

THE SUBSTITUTIONS, AND WHY THERE MUST BE SOME (Amendment A3: exactly these, nothing else)
------------------------------------------------------------------------------------------
A regeneration on a task branch cannot be byte-identical by plain ``report``, for two reasons that
are properties of the provenance design and not of any number:

1. every artifact embeds ``report``'s OWN ``git_commit`` / ``git_dirty`` at write time, so a
   regeneration at any other commit differs in those bytes while every value is equal; and
2. ``offline.transfer_curve.report`` re-derives ``BRIEF_37`` Amendment J1(c) per chunk and REFUSES
   a chunk whose commit differs from ``HEAD`` outside ``docs/`` -- which every hangzhou chunk does
   on a branch that changes ``offline/`` (``DEFERRED`` 84).

So each test substitutes ``_git_provenance`` with **the committed artifact's recorded pair** and,
for ``transfer_curve`` only, ``code_changed_since`` with ``[]``.  Both are existing patterns in
``tests/test_transfer_curve.py``; J1(c) keeps its own tests there.  With those two seams pinned,
EVERY other byte -- every row, statistic, target, key order -- must equal the committed file, which
is exactly what a per-intersection branch taken on a one-intersection scenario would break.

This file is added BEFORE ``offline/transfer_calibration.py`` is touched by P7.3d, on purpose: a
regression pin written after the refactor it guards can only ever agree with it.

GATE: ``RLTRAFFIC_OUTPUT_ROOT`` (default: this tree's ``output/``), holding the campaign work
directory each test names.  They are gitignored, so a clean clone skips -- naming the directory.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA = REPO_ROOT / "docs" / "data"


def _output_root() -> Path:
    return Path(os.environ.get("RLTRAFFIC_OUTPUT_ROOT", str(REPO_ROOT / "output")))


def _work_dir_or_skip(name: str, *, marker: str) -> Path:
    """The campaign's work directory, or a skip naming it and the file that proves it is one."""
    directory = _output_root() / name
    if not (directory / marker).is_file():
        pytest.skip(
            f"{directory} does not hold {marker}: set RLTRAFFIC_OUTPUT_ROOT to the output tree "
            f"that carries {name}/ (it is gitignored) to run this byte-identity regression"
        )
    return directory


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def test_p7_2b_calibration_regenerates_byte_identically_through_the_defaults(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``docs/data/p7_2b_calibration.json`` from ``output/p7_2b/``'s existing chunks.

    ``transfer_calibration`` has no J1(c) check, so ONE substitution applies here: the provenance
    pair.  The digest is also compared with the pin P7.3a's cells read their targets under
    (``transfer_curve.P7_2B_CALIBRATION_SHA256``), so this test and that pin cannot drift apart.

    *Mutation this is built against:* a per-intersection branch taken on the one-intersection
    scenario (a record, a statistic or a target changing shape) -> the bytes move -> this dies.
    """
    import offline.transfer_calibration as calibration
    import offline.transfer_curve as curve

    work = _work_dir_or_skip("p7_2b", marker="canary.json")
    committed = DATA / "p7_2b_calibration.json"
    recorded = json.loads(committed.read_text(encoding="utf-8"))
    pair = {"git_commit": recorded["git_commit"], "git_dirty": recorded["git_dirty"]}
    monkeypatch.setattr(calibration, "_git_provenance", lambda: dict(pair), raising=True)

    out = tmp_path / "p7_2b_calibration.json"
    calibration.report(work_dir=work, out_path=out, output_root=_output_root())

    assert out.read_bytes() == committed.read_bytes()
    assert _sha256(out.read_bytes()) == curve.P7_2B_CALIBRATION_SHA256
    assert calibration.SCENARIO_KEY == "cityflow1x1" == recorded["scenario_key"]


def _regenerates(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    *,
    work_name: str,
    artifact_name: str,
    stage: str | None = None,
    use_recorded_stage1: bool = False,
) -> None:
    """One campaign artifact, regenerated by the REAL ``report`` over its REAL work directory.

    Amendment A3's two substitutions, and **only** those two:

    1. ``code_changed_since -> []``. ``report`` re-derives J1(c) per chunk and refuses any chunk
       whose commit differs from ``HEAD`` outside ``docs/``; on a branch that changes ``offline/``
       that is every hangzhou chunk, by design (``DEFERRED`` 84).
    2. ``_git_provenance -> the committed artifact's own recorded pair``. Every artifact embeds
       ``report``'s own commit at write time, so a regeneration anywhere else differs in those
       bytes while every value is equal.

    With those two pinned, EVERY other byte must match: every cell row, every rho, every CI, and
    the key order. That is what a per-intersection branch taken on a one-intersection scenario, or
    any change to a shared helper, would break.
    """
    import offline.transfer_curve as curve

    work = _work_dir_or_skip(work_name, marker="canary.json")
    committed = DATA / artifact_name
    recorded = json.loads(committed.read_text(encoding="utf-8"))
    pair = {"git_commit": recorded["git_commit"], "git_dirty": recorded["git_dirty"]}
    monkeypatch.setattr(curve, "code_changed_since", lambda *a, **k: [], raising=True)
    monkeypatch.setattr(curve, "_git_provenance", lambda: dict(pair), raising=True)

    out = tmp_path / artifact_name
    kwargs: dict[str, object] = {
        "work_dir": work, "out_path": out, "out_root": _output_root().parent / "scenarios/draws",
        "output_root": _output_root(), "data_dir": DATA,
    }
    if stage is not None:
        kwargs["stage"] = stage
    if use_recorded_stage1:
        # ⚠️ Read from the artifact, never chosen here: `stage1_artifact.path` is recorded as an
        # ABSOLUTE path by the run that wrote it, so passing any other copy of the same file
        # changes one string and the comparison fails on a path rather than on a number. (That
        # the committed artifact embeds a machine-local path is P7.3a's property, not this
        # task's to change; it is why this argument is read rather than constructed.)
        recorded_path = Path(recorded["stage1_artifact"]["path"])
        if not recorded_path.is_file():
            pytest.skip(f"the recorded stage-1 artifact is not at {recorded_path}")
        kwargs["stage1_path"] = recorded_path
    curve.report(**kwargs)  # type: ignore[arg-type]

    assert out.read_bytes() == committed.read_bytes(), (
        f"{artifact_name} did not regenerate byte-identically; the hz1x1 path has moved"
    )


def test_p7_3a_zero_shot_regenerates_byte_identically(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """T-regress (b), the 4,700-cell campaign. *Mutation:* a per-intersection branch taken on the
    one-intersection scenario -> a row changes shape -> the bytes move."""
    _regenerates(
        monkeypatch, tmp_path, work_name="p7_3a", artifact_name="p7_3a_zero_shot.json",
        use_recorded_stage1=True,
    )


def test_p7_3b_anchor_regenerates_byte_identically(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """T-regress (b), the anchor stage."""
    _regenerates(
        monkeypatch, tmp_path, work_name="p7_3b_anchor", artifact_name="p7_3b_anchor.json",
        stage="anchor",
    )
