"""Gymnasium environment wrapping the MOSS (MObility Simulation System).

MOSS is a GPU-accelerated microscopic traffic simulator developed by
Tsinghua FibLab (https://github.com/tsinghua-fib-lab/moss).  This module
exposes :class:`MossEnv`, a drop-in alternative to
:class:`~envs.cityflow_env.CityFlowEnv` and
:class:`~envs.sumo_env.SumoEnv` for users that want to run
traffic-signal-control experiments on top of MOSS.

The env follows the same pattern as the other backends:

- Map / person inputs are protobuf files generated by ``mosstool``.
- One simulator instance is created on construction; :meth:`reset`
  rewinds the engine through a checkpoint instead of recreating it.
- Traffic-light phases are driven via MOSS's ``TlPolicy.MANUAL`` mode.
- All raw engine fields are translated to the same string-keyed
  intersection / lane vocabulary used by the other envs so that the
  shared :mod:`envs.base_traffic_env` plumbing and the
  agent code can stay backend-agnostic.
"""

from __future__ import annotations

import os
import tempfile
from collections.abc import Callable, Iterable
from pathlib import Path
from typing import Any

import numpy as np

from envs.base_traffic_env import BaseTrafficEnv
from envs.phase_control import AcyclicPhases, PhaseControl, PhaseSegment
from utils.common_utils import IntersectionInfo
from metrics import MossMetrics
from metrics.base import BaseMetrics
from states.base import StructuredFeature
from states.moss import MossStateFeatures


DEFAULT_JUNCTION_YELLOW_TIME = 0.0


class MossEnv(BaseTrafficEnv):
    """Gymnasium environment wrapping the MOSS traffic simulator.

    Parameters
    ----------
    map_file : str | Path
        Path to the MOSS map file (Protobuf format, ``.pb``) produced
        by ``mosstool``.
    person_file : str | Path
        Path to the MOSS person file (Protobuf format, ``.pb``).
    max_steps : int
        Maximum number of *agent* decision steps per episode.
    delta_time : int
        Simulation seconds between consecutive agent actions.  Converted
        to engine sub-steps via ``delta_time / step_interval``.
    global_reward_fn : str | callable
        Name of a registered reward function (see
        :mod:`rewards`) or a custom callable that accepts
        a metrics dict and returns a float.  Drives the scalar reward
        returned by ``step()`` (default ``"queue_length"``).
    local_reward_fn : str | callable
        Optional per-intersection reward.  When set, every intersection
        ``j`` receives ``global_reward_weight * global_reward +
        local_reward_fn(local_metrics[j])`` in
        ``info["intersections"][j]["reward"]``.
    global_reward_weight : float
        Weight of the global reward inside the per-intersection reward
        (default ``1.0``).
    phase_control_cls : type[PhaseControl]
        Strategy class used to translate agent actions into target
        phases (see :mod:`envs.phase_control`).
    phase_bounds : np.ndarray | None
        Optional ``(num_intersections, max_phases, 2)`` array of min/max
        phase-duration bounds applied via
        :meth:`BaseTrafficEnv.set_phase_durations`.
    metrics : Iterable[str] | None
        Names of metrics to enable (see :mod:`metrics`).
    name : str
        Task name passed to MOSS (used for output directory naming).
    step_interval : float
        Engine step interval in seconds (MOSS default ``1.0``).  Must be
        a positive divisor of ``delta_time`` to avoid rounding.
    seed : int
        Random seed forwarded to the MOSS engine.  Applied once at engine
        construction; MOSS cannot be re-seeded per episode, so
        ``reset(seed=...)`` does not vary traffic between episodes.
    device : int
        CUDA device index used by MOSS.
    output_dir : str | Path | None
        Optional AVRO output directory for MOSS.  ``None`` (default)
        disables file output.
    speed_stat_interval : int
        Interval (in steps) of MOSS's speed-statistics feature.  ``0``
        (default) disables it; required >0 for
        :meth:`moss.Engine.get_lane_average_vehicle_speed`.
    junction_yellow_time : float
        Extra clearance time in seconds that MOSS applies between traffic
        signal phases. Defaults to MOSS's native ``0``; positive values were
        measured to reduce Hangzhou throughput by delaying effective greens.
    verbose_level : str
        MOSS verbosity, one of ``"NO_OUTPUT"`` (default),
        ``"INIT_ONLY"`` or ``"ALL"``.
    """

    def __init__(
        self,
        map_file: str | Path,
        person_file: str | Path,
        max_steps: int = 3600,
        delta_time: int = 10,
        global_reward_fn: str | Callable[[dict[str, Any]], float] | None = None,
        phase_control_cls: type[PhaseControl] = AcyclicPhases,
        phase_bounds: np.ndarray | None = None,
        metrics: Iterable[str] | None = None,
        local_reward_fn: str | Callable[[dict[str, Any]], float] | None = None,
        global_reward_weight: float = 1.0,
        state_features: Iterable[str] | None = None,
        obs_norm: dict[str, float] | None = None,
        name: str = "moss",
        step_interval: float = 1.0,
        start_step: int = 0,
        seed: int = 43,
        device: int = 0,
        output_dir: str | Path | None = None,
        speed_stat_interval: int = 0,
        junction_yellow_time: float = DEFAULT_JUNCTION_YELLOW_TIME,
        verbose_level: str = "NO_OUTPUT",
        manual_control: bool = True,
    ) -> None:
        super().__init__(
            max_steps=max_steps,
            delta_time=delta_time,
            phase_control_cls=phase_control_cls,
            phase_bounds=phase_bounds,
            metrics=metrics,
            state_features=state_features,
            obs_norm=obs_norm,
        )

        self._map_path = str(Path(map_file).resolve())
        self._person_path = str(Path(person_file).resolve())
        if not os.path.exists(self._map_path):
            raise FileNotFoundError(f"MOSS map file missing: {self._map_path}")
        if not os.path.exists(self._person_path):
            raise FileNotFoundError(
                f"MOSS person file missing: {self._person_path}"
            )

        self._name = str(name)
        self._step_interval = float(step_interval)
        if self._step_interval <= 0.0:
            raise ValueError("step_interval must be > 0")
        # Phase-plan segments have integer second durations and _simulate()
        # advances the engine in step_interval chunks, so step_interval must
        # divide 1 s exactly or segment timing drifts silently (e.g. a 5 s
        # clearance at step_interval=2.0 would round to 4 s).
        _sub_steps_per_second = 1.0 / self._step_interval
        if abs(_sub_steps_per_second - round(_sub_steps_per_second)) > 1e-9:
            raise ValueError(
                "step_interval must evenly divide 1 second "
                f"(e.g. 1.0, 0.5, 0.25); got {self._step_interval}."
            )
        self._start_step = int(start_step)
        if self._start_step < 0:
            raise ValueError("start_step must be >= 0")
        self._seed = int(seed)
        self._device = int(device)
        self._output_dir = "" if output_dir is None else str(Path(output_dir))
        self._speed_stat_interval = int(speed_stat_interval)
        self._junction_yellow_time = float(junction_yellow_time)
        if self._junction_yellow_time < 0.0:
            raise ValueError("junction_yellow_time must be >= 0")
        self._verbose_level_name = str(verbose_level)
        self._manual_control = bool(manual_control)

        self._configure_rewards(
            global_reward_fn,
            local_reward_fn=local_reward_fn,
            global_reward_weight=global_reward_weight,
        )

        # Placeholders populated by _init_simulator().
        self._warned_reset_seed = False
        self._eng: Any = None
        self._initial_checkpoint: int | None = None
        self._junction_index_by_id: dict[str, int] = {}
        self._global_max_speed: float = 0.0
        self._intersections: list[IntersectionInfo] = []
        self._num_intersections = 0
        self._last_action_applied: np.ndarray = np.zeros(0, dtype=np.bool_)

        # Phase metadata read from the map protobuf and the index of the
        # all-red phase injected per junction (acyclic-transition modes).
        self._pb_phase_durations: dict[str, list[float]] = {}
        self._pb_phase_states: dict[str, list[str]] = {}
        self._all_red_phase_index: dict[str, int] = {}
        # Phase most recently pushed to the engine per junction id; used
        # by _simulate() so mid-step transition segments are not clobbered.
        self._applied_phase_by_id: dict[str, int] = {}
        self._tmp_map_dir: str | None = None
        self._effective_map_path = self._map_path
        if self._uses_synthetic_transition:
            # Acyclic-transition modes also need an all-red phase injected.
            self._effective_map_path = self._prepare_transition_map()
        elif self._phase_control_mode in {"cyclic", "resco_cyclic"}:
            # Cyclic / RESCo-cyclic don't inject any phase, but they (and
            # the default cyclic phase bounds) still need the per-junction
            # phase durations/states that MOSS doesn't expose at runtime.
            self._load_phase_metadata()

        # Boot MOSS, extract the map topology dynamically, and snapshot.
        self._init_simulator()
        self._setup_spaces()

        # Build the metrics object now that the engine is alive (will be
        # rebuilt in ``reset()`` for fresh episodes).
        self._init_metrics()

    # ------------------------------------------------------------------
    # Public properties
    # ------------------------------------------------------------------

    @property
    def engine(self) -> Any:
        """The underlying ``moss.Engine`` instance (or ``None``)."""
        return self._eng

    @property
    def junction_index_by_id(self) -> dict[str, int]:
        """Map intersection-id string -> MOSS junction index."""
        return self._junction_index_by_id

    @property
    def global_max_speed(self) -> float:
        """Largest per-lane ``max_speed`` (m/s) in the loaded map."""
        return self._global_max_speed

    def reset(
        self,
        *,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """See :meth:`BaseTrafficEnv.reset`.

        MOSS cannot be re-seeded at runtime: the engine is seeded once at
        construction (the ``seed`` parameter) and ``reset()`` rewinds it
        through a checkpoint, so every episode replays the same traffic.
        """
        if seed is not None and not self._warned_reset_seed:
            import warnings

            warnings.warn(
                "MossEnv cannot apply a per-episode engine seed: the MOSS "
                "engine is seeded once at construction and reset() restores "
                "a checkpoint, so episodes replay identical traffic. "
                "reset(seed=...) only re-seeds the env RNG.",
                RuntimeWarning,
                stacklevel=2,
            )
            self._warned_reset_seed = True
        return super().reset(seed=seed, options=options)

    # ------------------------------------------------------------------
    # MOSS helpers
    # ------------------------------------------------------------------

    def _import_moss(self):
        try:
            import moss  # noqa: WPS433
        except ImportError as exc:
            raise ImportError(
                "MOSS is not installed.  Install with `pip install "
                "python-moss` (Linux + CUDA only; see "
                "https://github.com/tsinghua-fib-lab/moss)."
            ) from exc
        return moss

    def _verbose_level(self, moss_mod):
        levels = getattr(moss_mod, "Verbosity", None)
        if levels is None:
            return 0
        return getattr(levels, self._verbose_level_name, levels.NO_OUTPUT)

    def _load_map_pb(self):
        """Parse the source MOSS map protobuf."""
        try:
            from pycityproto.city.map.v2 import map_pb2
        except ImportError as exc:
            raise ImportError(
                "Reading MOSS traffic-light phases requires the "
                "'pycityproto' package (installed alongside python-moss)."
            ) from exc

        map_pb = map_pb2.Map()
        with open(self._map_path, "rb") as f:
            map_pb.ParseFromString(f.read())
        return map_pb

    def _read_phase_metadata(self, map_pb) -> None:
        """Populate per-junction phase durations/states from *map_pb*.

        MOSS does not expose the fixed-program phase durations/states at
        runtime, but several phase controls need them: the acyclic modes
        to tell greens from file transitions, RESCo-cyclic to find the
        green phases and the file's clearance phases between them, and the
        default cyclic phase bounds to size green vs. yellow windows.
        """
        from pycityproto.city.map.v2 import light_pb2

        state_chars = {
            int(light_pb2.LIGHT_STATE_GREEN): "G",
            int(light_pb2.LIGHT_STATE_YELLOW): "y",
            int(light_pb2.LIGHT_STATE_RED): "r",
        }

        for junction in map_pb.junctions:
            if not junction.HasField("fixed_program"):
                continue
            phases = junction.fixed_program.phases
            if not phases:
                continue
            j_id = str(int(junction.id))
            self._pb_phase_durations[j_id] = [
                float(phase.duration) for phase in phases
            ]
            self._pb_phase_states[j_id] = [
                "".join(
                    state_chars.get(int(state), "r")
                    for state in phase.states
                )
                for phase in phases
            ]

    def _load_phase_metadata(self) -> None:
        """Read phase durations/states from the unmodified source map.

        Used by non-synthetic controls (cyclic / RESCo-cyclic) that drive
        the file's own phases by index and therefore must not alter the map.
        """
        self._read_phase_metadata(self._load_map_pb())

    def _prepare_transition_map(self) -> str:
        """Read TL phase metadata and write a map copy with all-red phases.

        MOSS can only switch phases by index, so the all-red clearance
        used by the acyclic-transition controls must exist as a real phase in
        the map: one is appended to every junction's fixed program (its
        index == the junction's original phase count) and the modified map
        is written to a temp file that the engine loads.  Also extracts
        per-junction phase durations/states, which MOSS does not expose at
        runtime, so the control can tell greens from file transitions.
        """
        from pycityproto.city.map.v2 import light_pb2

        map_pb = self._load_map_pb()
        self._read_phase_metadata(map_pb)

        for junction in map_pb.junctions:
            if not junction.HasField("fixed_program"):
                continue
            phases = junction.fixed_program.phases
            if not phases:
                continue
            j_id = str(int(junction.id))
            # phases still holds the original count here (all-red not yet
            # appended), so its length is the injected phase's index.
            self._all_red_phase_index[j_id] = len(phases)

            num_lanes = len(phases[0].states)
            all_red = phases.add()
            all_red.duration = 5.0
            all_red.states.extend([light_pb2.LIGHT_STATE_RED] * num_lanes)

        self._tmp_map_dir = tempfile.mkdtemp(prefix="moss_map_")
        out_path = os.path.join(self._tmp_map_dir, "map_all_red.pb")
        with open(out_path, "wb") as f:
            f.write(map_pb.SerializeToString())
        return out_path

    def _extract_intersections(self) -> list[IntersectionInfo]:
        """Build :class:`IntersectionInfo` from MOSS junction metadata.

        MOSS exposes phase-level (in_lane_indices, out_lane_indices)
        tuples per junction via ``get_junction_phase_lanes``.  We map
        each phase to a single virtual "roadlink" so the shared base
        env / phase-control machinery can treat MOSS like the other
        backends.
        """
        assert self._eng is not None
        engine = self._eng
        junc_index2id = engine.junc_index2id
        phase_counts = np.asarray(engine.get_junction_phase_counts())
        phase_lanes_all = engine.get_junction_phase_lanes()
        lane_index2id = engine.lane_index2id

        intersections: list[IntersectionInfo] = []
        idx_by_id: dict[str, int] = {}

        for j_idx in range(len(junc_index2id)):
            n_phases = int(phase_counts[j_idx]) if j_idx < len(phase_counts) else 0
            if n_phases <= 0:
                continue
            phase_lanes = phase_lanes_all[j_idx]
            n_phases = min(n_phases, len(phase_lanes))

            j_id_str = str(int(junc_index2id[j_idx]))

            # Hide the injected all-red phase (acyclic-transition modes)
            # from observation / action spaces: cap at the original count.
            pb_durations = self._pb_phase_durations.get(j_id_str)
            if pb_durations is not None:
                n_phases = min(n_phases, len(pb_durations))
            if n_phases == 0:
                continue

            incoming_ordered: list[str] = []
            outgoing_ordered: list[str] = []
            seen_in: set[str] = set()
            seen_out: set[str] = set()
            roadlink_lanes: list[tuple[list[str], list[str]]] = []
            phase_roadlink_mapping: list[list[int]] = []

            for phase_idx in range(n_phases):
                in_indices, out_indices = phase_lanes[phase_idx]
                rl_in: list[str] = []
                rl_in_seen: set[str] = set()
                for li in in_indices:
                    lid = str(int(lane_index2id[int(li)]))
                    if lid not in rl_in_seen:
                        rl_in.append(lid)
                        rl_in_seen.add(lid)
                    if lid not in seen_in:
                        incoming_ordered.append(lid)
                        seen_in.add(lid)
                rl_out: list[str] = []
                rl_out_seen: set[str] = set()
                for li in out_indices:
                    lid = str(int(lane_index2id[int(li)]))
                    if lid not in rl_out_seen:
                        rl_out.append(lid)
                        rl_out_seen.add(lid)
                    if lid not in seen_out:
                        outgoing_ordered.append(lid)
                        seen_out.add(lid)
                roadlink_lanes.append((rl_in, rl_out))
                # Each MOSS phase activates exactly its own virtual link.
                phase_roadlink_mapping.append([phase_idx])

            if not incoming_ordered:
                continue

            intersections.append(
                IntersectionInfo(
                    id=j_id_str,
                    incoming_lanes=incoming_ordered,
                    outgoing_lanes=outgoing_ordered,
                    num_phases=n_phases,
                    phase_roadlink_mapping=phase_roadlink_mapping,
                    phase_durations=list(
                        self._pb_phase_durations.get(j_id_str, [])
                    )[:n_phases],
                    phase_states=list(
                        self._pb_phase_states.get(j_id_str, [])
                    )[:n_phases],
                    roadlink_lanes=roadlink_lanes,
                )
            )
            idx_by_id[j_id_str] = j_idx

        intersections.sort(key=lambda x: x.id)
        self._junction_index_by_id = idx_by_id
        return intersections

    def _compute_global_max_speed(self) -> float:
        if self._eng is None:
            return 0.0
        try:
            speeds = [
                float(getattr(lane, "max_speed", 0.0))
                for lane in self._eng.id2lanes.values()
            ]
        except Exception:
            return 0.0
        speeds = [s for s in speeds if s > 0.0]
        return float(max(speeds)) if speeds else 0.0

    # ------------------------------------------------------------------
    # Abstract method implementations
    # ------------------------------------------------------------------

    def _init_simulator(self) -> None:
        moss = self._import_moss()

        if self._eng is None:
            verbosity = self._verbose_level(moss)
            self._eng = moss.Engine(
                name=self._name,
                map_file=self._effective_map_path,
                person_file=self._person_path,
                start_step=self._start_step,
                step_interval=self._step_interval,
                seed=self._seed,
                verbose_level=verbosity,
                speed_stat_interval=self._speed_stat_interval,
                junction_yellow_time=self._junction_yellow_time,
                output_dir=self._output_dir,
                device=self._device,
            )
            self._intersections = self._extract_intersections()
            self._num_intersections = len(self._intersections)
            if self._num_intersections == 0:
                raise ValueError(
                    "No controllable (TL-bearing) junctions found in MOSS map: "
                    f"{self._map_path}"
                )

            controlled = [
                self._junction_index_by_id[ix.id] for ix in self._intersections
            ]
            from moss import TlPolicy

            if self._manual_control:
                self._eng.set_tl_policy_batch(controlled, TlPolicy.MANUAL)
                self._set_tl_phases_batch(controlled, [0] * len(controlled))
            else:
                self._eng.set_tl_policy_batch(controlled, TlPolicy.FIXED_TIME)
            self._global_max_speed = self._compute_global_max_speed()
            # Snapshot the fresh state so reset() can rewind cheaply.
            self._initial_checkpoint = self._eng.make_checkpoint()
        else:
            assert self._initial_checkpoint is not None
            self._eng.restore_checkpoint(self._initial_checkpoint)
            controlled = [
                self._junction_index_by_id[ix.id] for ix in self._intersections
            ]
            from moss import TlPolicy

            if self._manual_control:
                # Defensively re-apply MANUAL policy in case the checkpoint
                # didn't carry it over.
                self._eng.set_tl_policy_batch(controlled, TlPolicy.MANUAL)
                self._set_tl_phases_batch(controlled, [0] * len(controlled))
            else:
                self._eng.set_tl_policy_batch(controlled, TlPolicy.FIXED_TIME)

        self._applied_phase_by_id = {}
        self._last_action_applied = np.zeros(
            self._num_intersections, dtype=np.bool_
        )

    def _set_tl_phases_batch(
        self, junction_indices: list[int], phase_indices: list[int]
    ) -> None:
        assert self._eng is not None
        if not junction_indices:
            return
        junction_indices = [int(j) for j in junction_indices]
        phase_indices = [int(p) for p in phase_indices]
        batch_setter = getattr(self._eng, "set_tl_phase_batch", None)
        if callable(batch_setter):
            batch_setter(junction_indices, phase_indices)
            return
        for j_index, phase in zip(junction_indices, phase_indices):
            self._eng.set_tl_phase(j_index, phase)

    def _simulate(self, num_steps: int) -> None:
        assert self._eng is not None
        if self._manual_control:
            # Re-assert the phase most recently pushed to the engine (not
            # the control's current phase, which is only updated at the
            # end of a step and would clobber mid-step transition
            # segments).  Falls back to the control right after reset.
            self._set_tl_phases_batch(
                [
                    self._junction_index_by_id[ix.id]
                    for ix in self._intersections
                ],
                [
                    self._applied_phase_by_id.get(
                        ix.id,
                        self._phase_controls[i].current_phase()
                        if i < len(self._phase_controls)
                        else 0,
                    )
                    for i, ix in enumerate(self._intersections)
                ],
            )
        # Convert agent ``delta_time`` (seconds) into engine sub-steps.
        n_engine_steps = max(
            1, int(round(float(num_steps) / self._step_interval))
        )
        self._eng.next_step(n_engine_steps)

    def _set_phase(
        self,
        ix_idx: int,
        phase: int,
        duration: int | None = None,
    ) -> None:
        _ = duration
        assert self._eng is not None
        if not self._manual_control:
            return
        ix_info = self._intersections[ix_idx]
        j_index = self._junction_index_by_id[ix_info.id]
        self._eng.set_tl_phase(int(j_index), int(phase))
        self._applied_phase_by_id[ix_info.id] = int(phase)

    def _apply_segment(self, ix_idx: int, segment: PhaseSegment) -> None:
        if segment.kind == "phase":
            self._set_phase(ix_idx, segment.phase, segment.duration)
            return
        if segment.kind == "all_red":
            assert self._eng is not None
            if not self._manual_control:
                return
            ix_info = self._intersections[ix_idx]
            all_red_index = self._all_red_phase_index.get(ix_info.id)
            if all_red_index is None:
                raise ValueError(
                    f"No all-red phase was injected for junction "
                    f"{ix_info.id}."
                )
            j_index = self._junction_index_by_id[ix_info.id]
            self._eng.set_tl_phase(int(j_index), int(all_red_index))
            self._applied_phase_by_id[ix_info.id] = int(all_red_index)
            return
        raise ValueError(
            f"Unsupported transition segment kind for MOSS: {segment.kind}"
        )

    def _create_metrics(self) -> BaseMetrics | None:
        if self._eng is None:
            return None
        return MossMetrics(
            engine=self._eng,
            intersections=self._intersections,
            metric_names=self._metric_names,
            delta_time=self.delta_time,
            global_max_speed=self._global_max_speed,
        )

    def _structured_features(self) -> dict[str, StructuredFeature]:
        return MossStateFeatures.structured_features()

    def _get_info(self) -> dict[str, Any]:
        assert self._eng is not None

        lane_vehicle_count = (
            self._metrics.lane_vehicle_count()
            if self._metrics is not None
            else {}
        )
        lane_waiting = (
            self._metrics.lane_waiting_vehicle_count()
            if self._metrics is not None
            else {}
        )

        intersections_info = self._build_intersections_info(
            lane_vehicle_count,
            lane_waiting,
        )

        try:
            vehicle_count = int(self._eng.get_running_person_count())
        except Exception:
            vehicle_count = 0
        try:
            sim_time = float(self._eng.get_current_time())
        except Exception:
            sim_time = float(self._step_count * self.delta_time)

        info: dict[str, Any] = {
            "sim_time": sim_time,
            "vehicle_count": vehicle_count,
            "average_travel_time": (
                self._metrics.get("average_travel_time")
                if self._metrics is not None
                else self._safe_average_travel_time()
            ),
            "lane_vehicle_count": lane_vehicle_count,
            "lane_waiting_vehicle_count": lane_waiting,
            "step": self._step_count,
            "intersections": intersections_info,
        }
        if self._metrics is not None:
            info["metrics"] = self._metrics.compute_all()
        return info

    def _safe_average_travel_time(self) -> float:
        if self._eng is None:
            return 0.0
        try:
            val = float(self._eng.get_finished_person_average_traveling_time())
        except Exception:
            return 0.0
        return 0.0 if val != val else val  # filter NaN

    # ------------------------------------------------------------------
    # Cleanup
    # ------------------------------------------------------------------

    def close(self) -> None:
        """Release the MOSS engine handle.

        MOSS owns GPU resources; dropping the Python reference is enough
        for them to be released by the C++ destructor.
        """
        self._eng = None
        self._initial_checkpoint = None

        if self._tmp_map_dir is not None and os.path.isdir(self._tmp_map_dir):
            import shutil

            shutil.rmtree(self._tmp_map_dir, ignore_errors=True)
            self._tmp_map_dir = None
